import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'footer.slogan': 'The future of decentralized finance on BSC. Stake, swap, and explore with confidence in the next generation of DeFi innovation.',
    // Header Navigation
    'header.nft': 'NFTs',
    'header.home': 'Home',
    'header.stake': 'Stake',
    'header.swap': 'Swap',
    'header.market': 'Market',
    'header.profile': 'Profile',
    'header.connectWallet': 'Connect Wallet',
    'header.language': 'Language',
    'header.connect': 'Connect',
    'stake.connectWallet': 'Connect Your Wallet',
    'stake.connectWalletDescription': 'Please connect your wallet to view your dashboard and portfolio.',
    
    // Hero Section
    'hero.title': 'The Future of DeFi',
    'hero.subtitle': 'The future of decentralized finance on BSC. Stake, swap, and explore with confidence in the next generation of DeFi innovation.',
    'hero.connect': 'Connect Wallet',
    'hero.learn': 'Learn More',
    'hero.headline': 'Your all-in-one decentralized platform',
    'hero.tagline': 'to stake, swap, and explore modX',
    'hero.cta1': 'Connect Wallet',
    'hero.cta2': 'Learn More',
    'hero.support': '24/7 Support',
    'hero.secure': '100% Secure',
    'hero.fees': '0% Hidden Fees',
    'hero.possibilities': 'Possibilities',
    
    // Features
    'features.stake.title': 'Stake & Earn',
    'features.stake.desc': 'Earn passive rewards by staking your modX tokens. Choose from flexible periods and watch your holdings grow.',
    'features.swap.title': 'Instant Swap',
    'features.swap.desc': 'Exchange tokens instantly with minimal fees and maximum security.',
    'features.explore.title': 'Explore DeFi',
    'features.explore.desc': 'Discover new opportunities in the decentralized finance ecosystem.',
    
    // Footer
    'footer.platform': 'Platform',
    'footer.about': 'About',
    'footer.docs': 'Documentation',
    'footer.community': 'Community',
    'footer.roadmap': 'Roadmap',
    'footer.faq': 'FAQ',
    'footer.copyright': '© 2025 modX. All rights reserved.',
    'footer.builtWith': 'Built with',
    'footer.by': 'by',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.stake': 'Stake',
    'nav.swap': 'Swap',
    'nav.market': 'Market',
    'nav.profile': 'Profile',
    'nav.connectWallet': 'Connect Wallet',
    'nav.language': 'Language',
    
    // Settings
    'settings.title': 'Settings',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.wallets': 'Wallets',
    'settings.transactionNotifications': 'Transaction Notifications',
    'settings.transactionNotificationsDesc': 'Get notified about your transactions',
    'settings.rewardNotifications': 'Reward Notifications',
    'settings.rewardNotificationsDesc': 'Get notified when you earn rewards',
    'settings.priceAlerts': 'Price Alerts',
    'settings.priceAlertsDesc': 'Get notified about price changes',
    'settings.stakeExpiry': 'Stake Expiry Alerts',
    'settings.stakeExpiryDesc': 'Get notified when stakes are about to expire',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.twoFactorDesc': 'Add an extra layer of security',
    'settings.sessionTimeout': 'Session Timeout (minutes)',
    'settings.sessionTimeoutDesc': 'Automatically log out after inactivity',
    'settings.general': 'General',
    'settings.theme': 'Theme',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.soundEffects': 'Sound Effects',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.twoFactorAuthDesc': 'Add an extra layer of security to your account',
    'settings.stakeExpiryAlerts': 'Stake Expiry Alerts',
    'settings.stakeExpiryAlertsDesc': 'Get notified when your stakes are about to expire',
    'settings.minutes': 'minutes',
    'settings.saveSettings': 'Save Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome back! Here\'s your portfolio overview',
    'dashboard.totalBalance': 'Total Balance',
    'dashboard.totalStaked': 'Total Staked',
    'dashboard.totalRewards': 'Total Rewards',
    'dashboard.price': 'Price',
    'dashboard.dailyChange': '24h Change',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.marketOverview': 'Market Overview',
    'dashboard.activeStakes': 'Active Stakes',
    'dashboard.noStakes': 'No active stakes yet',
    'dashboard.startStaking': 'Start staking to see your positions here',
    'dashboard.updating': 'Updating...',
    'dashboard.marketOverviewDesc': 'Real-time cryptocurrency prices and market data',
    'dashboard.yourBalance': 'Your Balance',
    'dashboard.availableStaking': 'Available for staking',
    'dashboard.connectWallet': 'Connect Your Wallet',
    'dashboard.connectWalletDescription': 'Please connect your wallet to view your dashboard and portfolio.',
    
    // Stake
    'stake.availableStaking': 'Available for Staking',
    'stake.readyToClaim': 'Ready to Claim',
    'stake.currentlyStaking': 'Currently Staking',
    'stake.title': 'Stake modX Tokens',
    'stake.subtitle': 'Earn passive rewards by staking your modX tokens. Choose from flexible periods and watch your holdings grow.',
    'stake.yourBalance': 'Your Balance',
    'stake.totalStaked': 'Total Staked',
    'stake.pendingRewards': 'Pending Rewards',
    'stake.stakingPools': 'Staking Pools',
    'stake.estimatedRewards': 'Estimated Rewards',
    'stake.lockPeriod': 'Lock Period',
    'stake.apy': 'APY',
    'stake.amount': 'Amount',
    'stake.days': 'days',
    'stake.stakeNow': 'Stake Now',
    'stake.claim': 'Claim',
    'stake.unstake': 'Unstake',
    'stake.stakeTokens': 'Stake Your Tokens',
    'stake.timeRemaining': 'Time Remaining',
    'stake.activePositions': 'Active Stake Positions',
    'stake.unlocked': 'Unlocked',
    'stake.lockEnds' : 'Lock Ends',
    'stake.noActivePositions' : 'No active stake positions yet',
    
    // Swap
    'swap.title': 'Swap Tokens',
    'swap.subtitle': 'Exchange tokens instantly with low fees',
    'swap.from': 'From',
    'swap.to': 'To',
    'swap.balance': 'Balance',
    'swap.exchangeRate': 'Exchange Rate',
    'swap.priceImpact': 'Price Impact',
    'swap.liquidityFee': 'Liquidity Provider Fee',
    'swap.swapTokens': 'Swap Tokens',
    'swap.recentSwaps': 'Recent Swaps',
    'swap.noHistory': 'No swap history yet',
    'swap.priceChart': 'Price Chart',
    'swap.marketStats': 'Market Stats',
    'swap.volume24h': '24h Volume',
    'swap.marketCap': 'Market Cap',
    'swap.price': 'Price',
    'swap.change24h': '24h Change',
    
    // Pool/Liquidity
    'pool.title': 'Liquidity Pool',
    'pool.addLiquidity': 'Add Liquidity',
    'pool.removeLiquidity': 'Remove Liquidity',
    'pool.yourPosition': 'Your Position',
    'pool.noPosition': 'No liquidity position found',
    'pool.noPositionDesc': 'Add liquidity to the modX/BNB pool to start earning fees',
    'pool.poolShare': 'Pool Share',
    'pool.lpTokens': 'LP Tokens',
    'pool.modXAmount': 'modX Amount',
    'pool.bnbAmount': 'BNB Amount',
    'pool.balance': 'Balance',
    'pool.addLiquidityBtn': 'Add Liquidity',
    'pool.removeLiquidityBtn': 'Remove Liquidity',
    'pool.adding': 'Adding Liquidity...',
    'pool.removing': 'Removing Liquidity...',
    'pool.history': 'Liquidity History',
    'pool.noHistory': 'No liquidity history yet',
    'pool.added': 'Added',
    'pool.removed': 'Removed',
    'pool.removePercent': 'Remove Percentage',
    'pool.confirmRemove': 'Confirm Remove',
    'pool.poolInfo': 'When you add liquidity, you receive LP tokens representing your share of the pool.',
    
    // Market
    'market.title': 'Market Overview',
    'market.subtitle': 'Real-time cryptocurrency prices and market data',
    'market.totalMarketCap': 'Total Market Cap',
    'market.volume24h': '24h Volume',
    'market.liveData': 'Live Data',
    'market.allTokens': 'All Tokens',
    'market.favorites': 'Favorites',
    'market.gainers': 'Gainers',
    'market.losers': 'Losers',
    'market.searchTokens': 'Search tokens...',
    'market.livePrices': 'Live Token Prices',
    'market.name': 'Name',
    'market.price': 'Price',
    'market.change': '24h Change',
    'market.volume': '24h Volume',
    'market.marketCap': 'Market Cap',
    'market.chart': 'Chart',
    'market.action': 'Action',
    'market.trade': 'Trade',
    'market.view': 'View',
    'market.overview': 'Market Overview',
    'market.viewChart': 'View Chart',
    'market.buyToken': '{token} Buy',
    'market.sellToken': '{token} Sell',
    'market.tradingChart': 'Trading Chart',
    'market.currentPrice': 'Current Price',
    'market.buy': 'Buy',
    'market.sell': 'Sell',
    
    // Profile
    'profile.title': 'User Profile',
    'profile.subtitle': 'Manage your account and view your portfolio',
    'profile.accountInfo': 'Account Information',
    'profile.walletAddress': 'Wallet Address',
    'profile.totalValue': 'Total Value',
    'profile.totalEarned': 'Total Earned',
    'profile.quickSettings': 'Quick Settings',
    'profile.notifications': 'Notifications',
    'profile.security': 'Security',
    'profile.connectedWallets': 'Connected Wallets',
    'profile.portfolioOverview': 'Portfolio Overview',
    'profile.totalBalance': 'Total Balance',
    'profile.totalStaked': 'Total Staked',
    'profile.transactionHistory': 'Transaction History',
    'profile.token': 'Token',
    'profile.balance': 'Balance',
    'profile.value': 'Value (USD)',
    'profile.noTransactions': 'No transactions yet',
    'profile.connectWallet': 'Connect Your Wallet',
    'profile.connectWalletDescription': 'Please connect your wallet to view your profile and portfolio.',
    
    // Stats
    'stats.tvl': 'Total Value Locked',
    'stats.staked': 'Total Staked',
    'stats.users': 'Total Users',
    'stats.apy': 'Average APY',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.hide': 'Hide',
    'common.show': 'Show',
    'common.all': 'All',
    'common.none': 'None',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.status': 'Status',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.failed': 'Failed',
    'common.connect': 'Connect',
    'common.disconnect': 'Disconnect',
  },
  tr: {
    // Header Navigation
    'header.home': 'Ana Sayfa',
    'header.nft': 'NFTs',
    'header.stake': 'Stake',
    'header.swap': 'Takas',
    'header.market': 'Piyasa',
    'header.profile': 'Profil',
    'header.connectWallet': 'Cüzdan Bağla',
    'header.language': 'Dil',
    'header.connect': 'Bağlan',
    
    // Hero Section
    'hero.title': 'DeFi\'nin Geleceği',
    'hero.subtitle': 'BSC üzerindeki merkezi olmayan finansın geleceği. Güvenle stake edin, takas yapın ve yeni nesil DeFi inovasyonunu keşfedin.',
    'hero.connect': 'Cüzdan Bağla',
    'hero.learn': 'Daha Fazla Öğren',
    'hero.headline': 'Hepsi bir arada merkeziyetsiz platformunuz',
    'hero.tagline': 'modX ile stake, takas ve keşfe çıkın',
    'hero.cta1': 'Cüzdan Bağla',
    'hero.cta2': 'Daha Fazla Öğren',
    'hero.support': '7/24 Destek',
    'hero.secure': '%100 Güvenli',
    'hero.fees': '%0 Gizli Ücret',
    'hero.possibilities': 'Olasılıklar',

    'stake.connectWallet': 'Cüzdanınızı Bağlayın',
    'stake.connectWalletDescription': ' Lütfen kontrol panelinizi ve portföyünüzü görüntülemek için cüzdanınızı bağlayın.',
    
    // Features
    'features.stake.title': 'Stake Et & Kazan',
    'features.stake.desc': 'modX tokenlarınızı stake ederek pasif ödüller kazanın. Esnek süreler seçin ve varlıklarınızın büyümesini izleyin.',
    'features.swap.title': 'Anında Takas',
    'features.swap.desc': 'Minimum ücret ve maksimum güvenlikle tokenları anında değiştirin.',
    'features.explore.title': 'DeFi Keşfet',
    'features.explore.desc': 'Merkezi olmayan finans ekosisteminde yeni fırsatları keşfedin.',
    
    // Footer
    'footer.slogan': 'BSC üzerindeki merkezi olmayan finansın geleceği. Güvenle stake edin, takas yapın ve yeni nesil DeFi inovasyonunu keşfedin.',
    'footer.platform': 'Platform',
    'footer.about': 'Hakkımızda',
    'footer.docs': 'Dokümantasyon',
    'footer.roadmap': 'Yol Haritası',
    'footer.faq': 'S.S.S.',
    'footer.community': 'Topluluk',
    'footer.support': 'Destek',
    'footer.contact': 'İletişim',
    'footer.builtWith': 'modART',
    'footer.by': 'Geliştiren',
    'footer.copyright': '© 2025 modX. Tüm hakları saklıdır.',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Hizmet Şartları',
    
    // Navigation
    'nav.dashboard': 'Kontrol Paneli',
    'nav.stake': 'Stake',
    'nav.swap': 'Takas',
    'nav.market': 'Piyasa',
    'nav.profile': 'Profil',
    'nav.connectWallet': 'Cüzdan Bağla',
    'nav.language': 'Dil',
    
    // Settings
    'settings.title': 'Ayarlar',
    'settings.notifications': 'Bildirimler',
    'settings.security': 'Güvenlik',
    'settings.wallets': 'Cüzdanlar',
    'settings.transactionNotifications': 'İşlem Bildirimleri',
    'settings.transactionNotificationsDesc': 'İşlemleriniz hakkında bildirim alın',
    'settings.rewardNotifications': 'Ödül Bildirimleri',
    'settings.rewardNotificationsDesc': 'Ödül kazandığınızda bildirim alın',
    'settings.priceAlerts': 'Fiyat Uyarıları',
    'settings.priceAlertsDesc': 'Fiyat değişiklikleri hakkında bildirim alın',
    'settings.stakeExpiry': 'Stake Süresi Uyarıları',
    'settings.stakeExpiryDesc': 'Stake süreniz dolmak üzereyken bildirim alın',
    'settings.twoFactor': 'İki Faktörlü Doğrulama',
    'settings.twoFactorDesc': 'Ek güvenlik katmanı ekleyin',
    'settings.sessionTimeout': 'Oturum Zaman Aşımı (dakika)',
    'settings.sessionTimeoutDesc': 'Hareketsizlik sonrası otomatik çıkış',
    'settings.general': 'Genel',
    'settings.theme': 'Tema',
    'settings.darkMode': 'Karanlık Mod',
    'settings.lightMode': 'Aydınlık Mod',
    'settings.soundEffects': 'Ses Efektleri',
    'settings.twoFactorAuth': 'İki Faktörlü Doğrulama',
    'settings.twoFactorAuthDesc': 'Hesabınıza ekstra güvenlik katmanı ekleyin',
    'settings.stakeExpiryAlerts': 'Stake Süresi Uyarıları',
    'settings.stakeExpiryAlertsDesc': 'Stake süreniz dolmak üzereyken bildirim alın',
    'settings.minutes': 'dakika',
    'settings.saveSettings': 'Ayarları Kaydet',
    
    // Dashboard
    'dashboard.title': 'Kontrol Paneli',
    'dashboard.subtitle': 'Tekrar hoş geldiniz! İşte portföyünüzün genel görünümü',
    'dashboard.totalBalance': 'Toplam Bakiye',
    'dashboard.totalStaked': 'Toplam Stake',
    'dashboard.totalRewards': 'Toplam Ödüller',
    'dashboard.price': 'Fiyat',
    'dashboard.dailyChange': '24s Değişim',
    'dashboard.quickActions': 'Hızlı İşlemler',
    'dashboard.recentTransactions': 'Son İşlemler',
    'dashboard.marketOverview': 'Piyasa Genel Bakış',
    'dashboard.activeStakes': 'Aktif Stake\'ler',
    'dashboard.noStakes': 'Henüz aktif stake yok',
    'dashboard.startStaking': 'Pozisyonlarınızı görmek için stake yapmaya başlayın',
    'dashboard.updating': 'Güncelleniyor...',
    'dashboard.marketOverviewDesc': 'Gerçek zamanlı kripto para fiyatları ve piyasa verileri',
    'dashboard.yourBalance': 'Bakiyeniz',
    'dashboard.availableStaking': 'Stake edebileceğin token Miktarı',
    'dashboard.connectWallet': 'Cüzdanınızı Bağlayın',
    'dashboard.connectWalletDescription': 'Kontrol panelinizi ve portföyünüzü görüntülemek için lütfen cüzdanınızı bağlayın.',
    
    // Stake
    'stake.availableStaking': 'Stake için Mevcut',
    'stake.title': 'modX Token Stake Et',
    'stake.subtitle': 'modX tokenlarınızı stake ederek pasif ödüller kazanın. Esnek süreler seçin ve varlıklarınızın büyümesini izleyin.',
    'stake.yourBalance': 'Bakiyeniz',
    'stake.totalStaked': 'Toplam Stake',
    'stake.activePositions': 'Aktif Stake Pozisyonları',
    'stake.pendingRewards': 'Bekleyen Ödüller',
    'stake.readyToClaim': 'Talep Etmeye Hazır',
    'stake.stakingPools': 'Stake Havuzları',
    'stake.estimatedRewards': 'Tahmini Ödüller',
    'stake.lockPeriod': 'Kilitlenme Süresi',
    'stake.currentlyStaking': 'Şu Anda Stake Ediliyor',
    'stake.apy': 'Yıllık Getiri',
    'stake.amount': 'Miktar',
    'stake.days': 'gün',
    'stake.stakeNow': 'Şimdi Stake Et',
    'stake.claim': 'Talep Et',
    'stake.unstake': 'Stake\'i Kaldır',
    'stake.stakeTokens': 'Tokenlarınızı Stake Edin',
    'stake.timeRemaining': 'Kalan Süre',
    'stake.unlocked': 'Kilidi Açıldı',
    'stake.lockEnds' : 'Kilit Bitişi',
    'stake.noActivePositions' : 'Henüz aktif stake pozisyonunuz yok',
    
    
    // Swap
    'swap.title': 'Token Takası',
    'swap.subtitle': 'Düşük komisyonlarla tokenları anında değiştirin',
    'swap.from': 'Gönderen',
    'swap.to': 'Alan',
    'swap.balance': 'Bakiye',
    'swap.exchangeRate': 'Döviz Kuru',
    'swap.priceImpact': 'Fiyat Etkisi',
    'swap.liquidityFee': 'Likidite Sağlayıcı Ücreti',
    'swap.swapTokens': 'Token Takası',
    'swap.recentSwaps': 'Son Takaslar',
    'swap.noHistory': 'Henüz takas geçmişi yok',
    'swap.priceChart': 'Fiyat Grafiği',
    'swap.marketStats': 'Piyasa İstatistikleri',
    'swap.volume24h': '24s Hacim',
    'swap.marketCap': 'Piyasa Değeri',
    'swap.price': 'Fiyat',
    'swap.change24h': '24s Değişim',
    
    // Pool/Liquidity
    'pool.title': 'Likidite Havuzu',
    'pool.addLiquidity': 'Likidite Ekle',
    'pool.removeLiquidity': 'Likidite Çıkar',
    'pool.yourPosition': 'Pozisyonunuz',
    'pool.noPosition': 'Likidite pozisyonu bulunamadı',
    'pool.noPositionDesc': 'Ücret kazanmaya başlamak için modX/BNB havuzuna likidite ekleyin',
    'pool.poolShare': 'Havuz Payı',
    'pool.lpTokens': 'LP Token',
    'pool.modXAmount': 'modX Miktarı',
    'pool.bnbAmount': 'BNB Miktarı',
    'pool.balance': 'Bakiye',
    'pool.addLiquidityBtn': 'Likidite Ekle',
    'pool.removeLiquidityBtn': 'Likidite Çıkar',
    'pool.adding': 'Likidite Ekleniyor...',
    'pool.removing': 'Likidite Çıkarılıyor...',
    'pool.history': 'Likidite Geçmişi',
    'pool.noHistory': 'Henüz likidite geçmişi yok',
    'pool.added': 'Eklendi',
    'pool.removed': 'Çıkarıldı',
    'pool.removePercent': 'Çıkarma Yüzdesi',
    'pool.confirmRemove': 'Çıkarmayı Onayla',
    'pool.poolInfo': 'Likidite eklediğinizde, havuzdaki payınızı temsil eden LP token alırsınız.',
    
    // Market
    'market.title': 'Piyasa Genel Bakış',
    'market.subtitle': 'Gerçek zamanlı kripto para fiyatları ve piyasa verileri',
    'market.totalMarketCap': 'Toplam Piyasa Değeri',
    'market.volume24h': '24s Hacim',
    'market.liveData': 'Canlı Veri',
    'market.allTokens': 'Tüm Tokenlar',
    'market.favorites': 'Favoriler',
    'market.gainers': 'Yükselenler',
    'market.losers': 'Düşenler',
    'market.searchTokens': 'Token ara...',
    'market.livePrices': 'Canlı Token Fiyatları',
    'market.name': 'İsim',
    'market.price': 'Fiyat',
    'market.change': '24s Değişim',
    'market.volume': '24s Hacim',
    'market.marketCap': 'Piyasa Değeri',
    'market.chart': 'Grafik',
    'market.action': 'İşlem',
    'market.trade': 'Al/Sat',
    'market.view': 'Görüntüle',
    'market.overview': 'Piyasa Genel Bakış',
    'market.viewChart': 'Grafik Görüntüle',
    'market.buyToken': '{token} Al',
    'market.sellToken': '{token} Sat',
    'market.tradingChart': 'İşlem Grafiği',
    'market.currentPrice': 'Güncel Fiyat',
    'market.buy': 'Al',
    'market.sell': 'Sat',
    
    // Profile
    'profile.title': 'Kullanıcı Profili',
    'profile.subtitle': 'Hesabınızı yönetin ve portföyünüzü görüntüleyin',
    'profile.accountInfo': 'Hesap Bilgileri',
    'profile.walletAddress': 'Cüzdan Adresi',
    'profile.totalValue': 'Toplam Değer',
    'profile.totalEarned': 'Toplam Kazanç',
    'profile.quickSettings': 'Hızlı Ayarlar',
    'profile.notifications': 'Bildirimler',
    'profile.security': 'Güvenlik',
    'profile.connectedWallets': 'Bağlı Cüzdanlar',
    'profile.portfolioOverview': 'Portföy Genel Bakış',
    'profile.totalBalance': 'Toplam Bakiye',
    'profile.totalStaked': 'Toplam Stake',
    'profile.transactionHistory': 'İşlem Geçmişi',
    'profile.token': 'Token',
    'profile.balance': 'Bakiye',
    'profile.value': 'Değer (USD)',
    'profile.noTransactions': 'Henüz işlem yok',
    'profile.connectWallet': 'Cüzdanınızı Bağlayın',
    'profile.connectWalletDescription': 'Profilinizi ve portföyünüzü görüntülemek için lütfen cüzdanınızı bağlayın.',
    
    // Stats
    'stats.tvl': 'Toplam Kilitli Değer',
    'stats.staked': 'Toplam Stake',
    'stats.users': 'Toplam Kullanıcı',
    'stats.apy': 'Ortalama Yıllık Getiri',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.cancel': 'İptal',
    'common.confirm': 'Onayla',
    'common.close': 'Kapat',
    'common.save': 'Kaydet',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'common.view': 'Görüntüle',
    'common.hide': 'Gizle',
    'common.show': 'Göster',
    'common.all': 'Tümü',
    'common.none': 'Hiçbiri',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.sort': 'Sırala',
    'common.date': 'Tarih',
    'common.amount': 'Miktar',
    'common.status': 'Durum',
    'common.completed': 'Tamamlandı',
    'common.pending': 'Beklemede',
    'common.failed': 'Başarısız',
    'common.connect': 'Bağlan',
    'common.disconnect': 'Bağlantıyı Kes',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
